/*
 * This source file was generated by the Gradle 'init' task
 */
package app.src.test.java.org.example;



import ticket_booking.App;

// import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    private void assertNotNull(String string, String greeting) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'assertNotNull'");
    }
}
